{% set version = "0.5.0" %}
{% set major,minor,patch = version.split('.') %}

package:
  name: aha
  version: {{ version }}

source:
  url: https://github.com/theZiz/aha/archive/0.5.tar.gz
  sha256: 6f8b044bee9760a1a85dffbc362e532d7dd91bb20b7ed4f241ff1119ad74758f

build:
  number: 0 

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [not win]

test:
  commands:
    - aha -h

about:
  home: https://github.com/theZiz/aha
  license: MPL
  license_file: LICENSE.MPL1.1
  summary: "Converts ANSI escape sequences of a unix terminal to HTML code."
  description: |
    Converts ANSI escape sequences of a unix terminal to HTML code.
  doc_url: https://github.com/theZiz/aha
  dev_url: https://github.com/theZiz/aha

extra:
  recipe-maintainers:
    - bsipos
